In [1]:
import numpy as np
from sklearn.feature_selection import SelectKBest, f_classif
X = np.array([
    [1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0.697, 0.460],
    [2, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0.774, 0.376],
    [3, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0.666, 0.091],
    [4, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0.245, 0.057],
])
y = [1, 1, 0, 0]

sk = SelectKBest(f_classif)
sk.fit_transform(X, y)
sk.scores_


array([ 8.        ,  0.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  0.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.71207075, 57.64052606])

In [4]:
import numpy as np
from sklearn.feature_selection import SelectKBest, chi2

X = np.array([
    [1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0.697, 0.460],
    [2, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0.774, 0.376],
    [3, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0.666, 0.091],
    [4, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0.245, 0.057],
])
y = [1, 1, 0, 0]

sk = SelectKBest(chi2)
sk.fit_transform(X, y)
sk.scores_


array([1.6       , 0.        , 1.        , 1.        , 1.        ,
       1.        , 2.        , 0.        , 1.        , 1.        ,
       1.        , 2.        , 1.        , 2.        , 1.        ,
       1.        , 0.        , 0.13165407, 0.48104065])

In [2]:
import numpy as np
from sklearn.feature_selection import SelectKBest, mutual_info_classif

X = np.array([
    [1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0.697, 0.460],
    [2, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0.774, 0.376],
    [3, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0.666, 0.091],
    [4, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0.245, 0.057],
])
y = [1, 1, 0, 0]

sk = SelectKBest(mutual_info_classif)
sk.fit_transform(X, y)
sk.scores_

array([0.58333333, 0.        , 0.        , 0.20833333, 0.        ,
       0.        , 0.83333333, 0.        , 0.        , 0.20833333,
       0.        , 0.83333333, 0.20833333, 0.83333333, 0.08333333,
       0.        , 0.        , 0.        , 0.83333333])

In [6]:
import numpy as np

X = np.array([
    [1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0.697, 0.460, 1],
    [2, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0.774, 0.376, 1],
    [3, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0.666, 0.091, 0],
    [4, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0.245, 0.057, 0],
])
corr = np.corrcoef(X, rowvar=False)
corr[-1,:]

array([-0.89442719,  0.        , -0.57735027,  0.57735027, -0.57735027,
       -0.57735027,  1.        ,  0.        ,  0.57735027, -0.57735027,
       -0.57735027,  1.        , -0.57735027,  1.        , -0.57735027,
       -0.57735027,  0.67912971,  0.9830899 ,  1.        ])