In [44]:
import numpy as np
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import SimpleImputer, IterativeImputer

X = np.array([
    [1, '青绿', '蜷缩', '浊响', '清晰', '凹陷', '硬滑', 0.697, np.nan],
    [2, '乌黑', '蜷缩', '沉闷', '清晰', '凹陷', '硬滑', 0.774, 0.376],
    [3, '乌黑', '稍蜷', '沉闷', '-', '稍凹', '硬滑', 0.666, 0.091],
    [4, '浅白', '硬挺', '清脆', '模糊', '平坦', '硬滑', 0.245, 0.057],
])
imp_mean = SimpleImputer(strategy='mean')
imp_mean.fit_transform(X[:, 7:9]) # 用均值填充


array([[0.697     , 0.17466667],
       [0.774     , 0.376     ],
       [0.666     , 0.091     ],
       [0.245     , 0.057     ]])

In [45]:
imp_median = SimpleImputer(strategy='median')
imp_median.fit_transform(X[:, 7:9]) # 用中位数填充

array([[0.697, 0.091],
       [0.774, 0.376],
       [0.666, 0.091],
       [0.245, 0.057]])

In [46]:
imp_frequent = SimpleImputer(missing_values='-', strategy='most_frequent')
imp_frequent.fit_transform(X[:, 1:7].astype('object')) # 用众数填充

array([['青绿', '蜷缩', '浊响', '清晰', '凹陷', '硬滑'],
       ['乌黑', '蜷缩', '沉闷', '清晰', '凹陷', '硬滑'],
       ['乌黑', '稍蜷', '沉闷', '清晰', '稍凹', '硬滑'],
       ['浅白', '硬挺', '清脆', '模糊', '平坦', '硬滑']], dtype=object)

In [49]:
# 回归器默认采用BayesianRidge 也可选DecisionTreeRegressor ExtraTreesRegressor KNeighborsRegressor
imp_iter = IterativeImputer()
imp_iter.fit_transform(X[:, 7:9])

array([[0.697     , 0.20908713],
       [0.774     , 0.376     ],
       [0.666     , 0.091     ],
       [0.245     , 0.057     ]])