特征标准化

In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler, MaxAbsScaler, scale

X = np.array([
    [1, '青绿', '蜷缩', '浊响', '清晰', '凹陷', '硬滑', 0.697, 0.460],
    [2, '乌黑', '蜷缩', '沉闷', '清晰', '凹陷', '硬滑', 0.774, 0.376],
    [3, '乌黑', '稍蜷', '沉闷', '稍糊', '稍凹', '硬滑', 0.666, 0.091],
    [4, '浅白', '硬挺', '清脆', '模糊', '平坦', '硬滑', 0.245, 0.057],
])
MinMaxScaler().fit_transform(X[:, 7:9])

array([[0.85444234, 1.        ],
       [1.        , 0.79156328],
       [0.79584121, 0.08436725],
       [0.        , 0.        ]])

In [6]:
MaxAbsScaler().fit_transform(X[:, 7:9])

array([[0.9005168 , 1.        ],
       [1.        , 0.8173913 ],
       [0.86046512, 0.19782609],
       [0.31653747, 0.12391304]])

In [3]:
x = scale(X[:, 7:9])
x

array([[ 0.49236904,  1.22314674],
       [ 0.86589038,  0.74303307],
       [ 0.34199032, -0.88592404],
       [-1.70024974, -1.08025576]])

In [4]:
x.mean(axis=0)

array([-1.11022302e-16, -1.66533454e-16])