In [5]:
import numpy as np
from sklearn.decomposition import PCA

X = np.array([
    [1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0.697, 0.460],
    [2, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0.774, 0.376],
    [3, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0.666, 0.091],
    [4, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0.245, 0.057],
])

pca = PCA(n_components=3)
pca.fit(X)
print(pca.explained_variance_ratio_)

X = pca.transform(X)
X

[0.61994982 0.29044141 0.08960877]


array([[-2.00117642, -0.8994997 , -0.60604575],
       [-1.03113008,  0.31462009,  1.00575703],
       [ 0.69000731,  1.72221775, -0.46027295],
       [ 2.34229919, -1.13733814,  0.06056167]])

In [31]:
XX = VarianceThreshold(threshold=0.01).fit_transform(X)
XX

array([[1.   , 0.   , 0.   , 1.   , 0.   , 0.   , 1.   , 0.   , 1.   ,
        0.   , 0.   , 1.   , 0.   , 1.   , 0.   , 0.   , 0.697, 0.46 ],
       [2.   , 1.   , 0.   , 0.   , 0.   , 0.   , 1.   , 1.   , 0.   ,
        0.   , 0.   , 1.   , 0.   , 1.   , 0.   , 0.   , 0.774, 0.376],
       [3.   , 1.   , 0.   , 0.   , 0.   , 1.   , 0.   , 1.   , 0.   ,
        0.   , 0.   , 0.   , 1.   , 0.   , 0.   , 1.   , 0.666, 0.091],
       [4.   , 0.   , 1.   , 0.   , 1.   , 0.   , 0.   , 0.   , 0.   ,
        1.   , 1.   , 0.   , 0.   , 0.   , 1.   , 0.   , 0.245, 0.057]])

In [30]:
XX.shape

(4, 18)